package com.hbcun.business.bs.entity.vo.ems.util;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import com.hbcun.business.bs.constant.EmsConfig;

import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-04-16T14:17:25.628+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "ILoadData", 
                wsdlLocation = EmsConfig.WEB_SERVICE_URL,
                  targetNamespace = "http://wsserver.hzws.routdata.com") 
public class ILoadData extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://wsserver.hzws.routdata.com", "ILoadData");
    public final static QName ILoadDataHttpPort = new QName("http://wsserver.hzws.routdata.com", "ILoadDataHttpPort");
    static {
        URL url = null;
        try {
            url = new URL(EmsConfig.WEB_SERVICE_URL);
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ILoadData.class.getName())
                .log(java.util.logging.Level.INFO, "Can not initialize the default wsdl from {0}", EmsConfig.WEB_SERVICE_URL);
        }
        WSDL_LOCATION = url;
    }

    public ILoadData(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ILoadData(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ILoadData() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ILoadDataPortType
     */
    @WebEndpoint(name = "ILoadDataHttpPort")
    public ILoadDataPortType getILoadDataHttpPort() {
        return super.getPort(ILoadDataHttpPort, ILoadDataPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ILoadDataPortType
     */
    @WebEndpoint(name = "ILoadDataHttpPort")
    public ILoadDataPortType getILoadDataHttpPort(WebServiceFeature... features) {
        return super.getPort(ILoadDataHttpPort, ILoadDataPortType.class, features);
    }

}
