package com.hbcun.business.bs.entity.vo.ems.util;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-04-16T14:17:25.617+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://wsserver.hzws.routdata.com", name = "ILoadDataPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ILoadDataPortType {

    @WebResult(name = "out", targetNamespace = "http://wsserver.hzws.routdata.com")
    @RequestWrapper(localName = "CallServiceReturn", targetNamespace = "http://wsserver.hzws.routdata.com", className = "com.hbcun.business.bs.entity.vo.ems.util.CallServiceReturn")
    @WebMethod(operationName = "CallServiceReturn")
    @ResponseWrapper(localName = "CallServiceReturnResponse", targetNamespace = "http://wsserver.hzws.routdata.com", className = "com.hbcun.business.bs.entity.vo.ems.util.CallServiceReturnResponse")
    public java.lang.String callServiceReturn(
        @WebParam(name = "in0", targetNamespace = "http://wsserver.hzws.routdata.com")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://wsserver.hzws.routdata.com")
    @RequestWrapper(localName = "CallService", targetNamespace = "http://wsserver.hzws.routdata.com", className = "com.hbcun.pojo.ems.util.CallService")
    @WebMethod(operationName = "CallService")
    @ResponseWrapper(localName = "CallServiceResponse", targetNamespace = "http://wsserver.hzws.routdata.com", className = "com.hbcun.pojo.ems.util.CallServiceResponse")
    public java.lang.String callService(
        @WebParam(name = "in0", targetNamespace = "http://wsserver.hzws.routdata.com")
        java.lang.String in0
    );
}
