package com.hbcun.business.bs.entity.vo.eplink.util;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-04-10T15:20:34.832+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://ws.newyork.zjport.gov.cn/", name = "ReceivedDeclareService")
@XmlSeeAlso({ObjectFactory.class})
public interface ReceivedDeclareService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkReceived", targetNamespace = "http://ws.newyork.zjport.gov.cn/", className = "com.hbcun.business.bs.entity.vo.eplink.util.CheckReceived")
    @WebMethod
    @ResponseWrapper(localName = "checkReceivedResponse", targetNamespace = "http://ws.newyork.zjport.gov.cn/", className = "com.hbcun.business.bs.entity.vo.eplink.util.CheckReceivedResponse")
    public java.lang.String checkReceived(
        @WebParam(name = "xmlStr", targetNamespace = "")
        java.lang.String xmlStr,
        @WebParam(name = "xmlType", targetNamespace = "")
        java.lang.String xmlType,
        @WebParam(name = "sourceType", targetNamespace = "")
        java.lang.String sourceType
    );
}
