
package com.hbcun.business.bs.entity.vo.eplink.util;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-04-10T15:20:34.788+08:00
 * Generated source version: 3.0.4
 * 
 */
public final class ReceivedDeclareService_ReceivedDeclareServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.ws.newyork.zjport.gov.cn/", "ReceivedDeclareServiceImplService");
    
    private ReceivedDeclareService_ReceivedDeclareServiceImplPort_Client() {
    	
    }

    /**
     * 向电子口岸发送数据
     * @param xml			xml数据
     * @param xmlType		businessType
     * @param sourceType 	<code>sourceType == null ? "1" : sourceType</code> 
     * @return
     */
    public static String sendRequestData(String xml, String xmlType, final String sourceType){
    	
    	String newSourceType = sourceType == null ? "1" : sourceType;
    	URL wsdlURL = ReceivedDeclareServiceImplService.WSDL_LOCATION;
    	ReceivedDeclareServiceImplService ss = new ReceivedDeclareServiceImplService(wsdlURL, SERVICE_NAME);
    	ReceivedDeclareService port = ss.getReceivedDeclareServiceImplPort(); 
    	String _checkReceived__return = port.checkReceived(xml, xmlType, newSourceType);
        return _checkReceived__return;
    }

}
